version: '3.7'

services: 

  main_ms_data_sharing:
    container_name: main_ms_data_sharing
    build:
      context: ./ms-data-sharing
      target: development
    volumes:
      - ./ms-data-sharing:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    command: npm run start:debug
    env_file: 
      - ./ms-data-sharing/.env
    networks: 
      - orchestrate
      - default
      

  main:
    container_name: main
    build:
      context: ./api-items
      target: development
    volumes:
      - ./api-items:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3002:3002
      - 9230:9230
    command: npm run start:debug
    env_file:
      - ./api-items/.env
    depends_on: 
      - postgres
      - main_ms_data_sharing
    networks:
      - default

  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: nesta
      POSTGRES_USER: admin
      POSTGRES_DB: items
      PG_DATA: /var/lib/postgresql/data-api
    ports:
      - 5432:5432
    env_file:
      - ./api-items/.env
    volumes:
      - pgdata:/var/lib/postgresql/data-api
    networks:
      - default

volumes:
  pgdata:

networks:
#  app:
#    name: app_default
  orchestrate:
    external:
      name: deps_orchestrate
