version: '3.7'

services: 
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9230:9230
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - net
    depends_on: 
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - ${PGADMIN_PORT}:81
    networks: 
      - net
networks:
  net:
volumes:
  pgdata:
  pgadmin:
    
